// main.js
console.log("main cargado");
import '/frontend/src/js/components/parkalia_code_verify.js';
import '/frontend/src/js/components/parkalia_forgot_password.js';
import '/frontend/src/js/components/parkalia_login.js';
import '/frontend/src/js/components/parkalia_reset_password.js';
import '/frontend/src/js/components/parkalia_top_offers.js';
import '/frontend/src/js/components/parkalia_navbar_global.js';
import '/frontend/src/js/components/parkalia_sidebar_principal.js';
import '/frontend/src/js/components/parkalia_drop-down_menu.js';

import '/frontend/src/js/components/registers/parkalia_register_parking_lot.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot1.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot2.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot3.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot4.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot5.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot6.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot7.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot8.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot9.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot10.js';
import '/frontend/src/js/components/registers/parkalia_register_parking_lot11.js';
