// main.js
console.log("main cargado");
import '/frontend/src/js/components/parkalia_code_verify.js';
import '/frontend/src/js/components/parkalia_forgot_password.js';
import '/frontend/src/js/components/parkalia_login.js';
import '/frontend/src/js/components/parkalia_reset_password.js';
import '/frontend/src/js/components/parkalia_top_offers.js';
import '/frontend/src/js/components/parkalia_navbar_global.js';
import '/frontend/src/js/components/parkalia_sidebar_principal.js';
import '/frontend/src/js/components/parkalia_drop-down_menu.js';

import '/frontend/src/js/components/registers/parkalia_register.js';
import '/frontend/src/js/components/registers/parkalia_register1.js';
import '/frontend/src/js/components/registers/parkalia_register2.js';
import '/frontend/src/js/components/registers/parkalia_register3.js';
import '/frontend/src/js/components/registers/parkalia_register4.js';
import '/frontend/src/js/components/registers/parkalia_register5.js';
import '/frontend/src/js/components/registers/parkalia_register6.js';
import '/frontend/src/js/components/registers/parkalia_register7.js';
import '/frontend/src/js/components/registers/parkalia_register8.js';
import '/frontend/src/js/components/registers/parkalia_register9.js';
import '/frontend/src/js/components/registers/parkalia_register10.js';
import '/frontend/src/js/components/registers/parkalia_register11.js';
